version: "3"

services:
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production.local
    volumes:
      - /user/src/app/node_modules
    ports:
      - ${PORT}:${PORT}
    command: yarn start
