version: "3"

services:
  sonarqube:
    image: sonarqube:lts-community
    ports:
      - 9000:9000

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/user/src/app
      - /user/src/app/node_modules
    env_file:
      - .env.development.local
    ports:
      - ${PORT}:${PORT}
    command: yarn dev
