version: "3"

services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/user/src/app
      - /user/src/app/node_modules
    env_file:
      - .env.development.local
    ports:
      - ${PORT}:${PORT}
    command: yarn dev
